@startuml Classes
left to right direction

class 業者 {
    業者コード
    名称
    住所
    電話番号
}

class 商品 {
    商品コード
    名称
    単価
}

class 発注セット {
    商品名
    商品単価
    数量
    /小計
}
note bottom of 発注セット
    発注時点での商品名と単価である必要があるため、
    商品コードから商品を参照する作りにはしない。
end note

class 発注書 {
    業者名称
    業者住所
    業者電話番号
    発注日時
    発注セットリスト
    /合計金額
}
note bottom of 発注書
    発注時点での業者の名称や連絡先である必要があるため、
    業者コードから業者を参照する作りにはしない。
end note

業者 "1" -- "*" 商品
発注書 "1" -- "1..*" 発注セット
業者 - "生成" 発注書
商品 - "生成" 発注セット
@end
