@startuml Classes
left to right direction

class 業者 {
    業者コード
    名称
    住所
    電話番号
}

class 商品 {
    商品コード
    名称
    単価
}

class 発注セット {
    商品コード
    数量
    /小計
}

class 発注書 {
    業者コード
    発注セットリスト
}

業者 "1" -- "*" 商品
発注書 "1" -- "1..*" 発注セット
発注書 "*" -- "1" 業者
@end
