@startuml RegisterTraders
participant "管理者" as Admin
participant "システム" as System
participant "業者" as Trader

Admin -> System: 業者情報・ID・パスワード入力
activate System
System -> System: 業者情報登録
System -> Admin: 登録完了
deactivate System
Admin -> Trader: 登録したIDとパスワードを通知

Trader -> System: 通知されたIDとパスワードを使ってログイン
activate System
System -> System: 認証
System -> Trader: ログイン結果通知

Trader -> System: 商品情報入力
System -> System: 商品情報登録
System -> Trader: 結果出力
deactivate System
@end
